name: Master Repo Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        run: npm install

      - name: Run Node.js Application
        run: node test.js
        env:
          GITHUB_TOKEN_MASTER: ${{ secrets.GITHUB_TOKEN }}
