name: Node.js App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Generate Directory Tree
        uses: zakarialaoui10/dir2tree@main
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
          OWNER : ${{github.repository_owner}}
          NAME  : ${{github.event.repository.name}}
