name: Node.js App CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.CUSTOM_TOKEN }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 18.14.0
      - uses: zakarialaoui10/dir2tree@main
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}
