name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm start
    - name: Check for changes
      id: git-status
      run: |
        if [[ -n $(git status -s) ]]; then
          echo "::set-output name=changed::true"
        else
          echo "::set-output name=changed::false"
        fi
      shell: bash
    - name: Commit & Push
      if: steps.git-status.outputs.changed == 'true'
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A .
        git commit -m "generated"
        git push
