name: Node.js App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Write File
        uses: actions/write-file@v1
        with:
           path: myfile.txt
           contents: Hello, world!

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          permissions: write

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Node
        run: node index.js
