name: Node.js App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use a supported Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Create a Directory
        run: mkdir myappdata
        working-directory: ${{ github.workspace }}

      - name: Run Node.js App
        run: node index2.js
        working-directory: ${{ github.workspace }}/myappdata


      - name: Run Node.js App
        run: node index2.js
        working-directory: ${{ github.workspace }}
